spring:
  application:
    name: TaskFlow
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_y7MS8LI4ZQn1F8nnyFK@authorization-demo-mysql-os96.l.aivencloud.com:17470/mo_demo?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_y7MS8LI4ZQn1F8nnyFK
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: mySecretKeyForTaskFlowApplication123456789
  expiration: 86400

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    mo.demo: DEBUG

cors:
  allowed-origins: "*"
